
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/site_manage_system?serverTimezone = GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
